import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const initialCompanies = [
  { zona: "ZONA 1", nombre: "Masivos S.A.", direccion: "J.E. Rodó 6142, Mataderos, CABA", barrio: "Mataderos", telefono: "(011) 4687-0556 / 4140-2831", email: "ventas@masivos.com", url: "www.masivos.com", notas: "Se habló con Lusmila de Recepción por el número 11-4686-6363 indicó que solo atienden por correo para realizar citas de atención a proveedores escribir al correo: guillermo@masivos.com" },
  { zona: "ZONA 1", nombre: "La Dolce S.R.L.", direccion: "Av. Directorio 5961, Mataderos, CABA", barrio: "Mataderos", telefono: "0810-222-3646", email: "No especificado", url: "www.ladolce.com.ar" },
  { zona: "ZONA 1", nombre: "Distribuidora Mar y Mar Mataderos", direccion: "Av. Juan Bautista Alberdi 5918, Mataderos, CABA", barrio: "Mataderos", telefono: "(011) 4686-3198 / 11-4474-8502", email: "No especificado", url: "golmarymar.com.ar", notas: "Se habló con álvaro de la caja he indicó que las compras la manejas desde la sucursal Directorio 492, CABA. pero es previo cita a he indico que escribiera al correo: info@golmarymar.com.ar con atencion a Jose Luis." },
  { zona: "ZONA 6", nombre: "Supermercado Mayorista Asia Oriental", direccion: "Mendoza 1650, Barrio Chino, Belgrano, CABA", barrio: "Belgrano", telefono: "+54 9 11 6010-4368", email: "info@asiabaires.com", url: "asiabaires.mitiendanube.com", notas: "Solo comercializan productos Importados" },
  { zona: "ZONA 6", nombre: "Supermercado Casa China", direccion: "Arribeños 2263/2163, Barrio Chino, Belgrano, CABA", barrio: "Belgrano", notas: "Solo comercializan productos Importados" },
  { zona: "ZONA 6", nombre: "Supermercado Hua Fu Chen", direccion: "Olazábal 1673, Barrio Chino, Belgrano, CABA", barrio: "Belgrano", notas: "Branca me indico que no comercializan esos productos pero me indico su numero de celular para que le pase el catalogo y lista de precios ya que igual se los mostraba a su jefa para estudiar la posibilidad 1121700088" },
  { zona: "CORREO", nombre: "Distribuidora PG", direccion: "Operación logística directa a CABA", telefono: "11 7368-2430 / Wsapp", url: "distribuidorapg.com.ar", notas: "Se envio whatsapp pàra explorara a la distribuidora buscando una contactacion con el responsable de compras. Denis es mi nombre. Paso esta data al sector compras. muy desprolijo Cualquier cosa se comunican. Gracias" },
  { zona: "ZONA 7", nombre: "Los Gringos", direccion: "D'Onofrio 130, Ciudadela", barrio: "Ciudadela", telefono: "11 5117-3115", url: "www.golosinaslosgringos.com.ar", notas: "Hable con Santiago es el encargado de compras, indicó que enviará los precios al whatsapp 11 5117-3115 se interesó por los Snack no tienen correo solo atiendo por Whatsapp. resaltó que quien toma la decisión es Nancy. Segunda visita se habla con santiago indica su numero personal y confirma que recibe la informacion para pasarla a Nancy quien toma la deciion se agenda para otra visita" },
  { zona: "ZONA 4", nombre: "La Golosinería", direccion: "Av Rivadavia 2052", barrio: "Balvanera", url: "www.lagolosineria.com.ar", notas: "Se habla con Nicolas encargado de la Local Principal de la RED tienen 8 suculsales el indica que solo atienden por correo para agendar una reunion indica el correo info@lagolosineria.com.ar" },
  { zona: "ZONA 2", nombre: "Dulsisa Golosinas", direccion: "Av. Raúl Scalabrini Ortiz 445", barrio: "Villa Crespo", email: "dulsisa@hotmail.com", url: "www.dulsisa.com", notas: "Se hablo con Jaime indico el correo y solicito la lista de precios y el catalogo conoce la galletitas pero nunca las vendio tiene 3 locales. Segunda visita No estaba Jaime el dueño se reprograma visita" },
  { zona: "ZONA 4", nombre: "FIORITO Mayorista Golosinas-Galletitas", direccion: "Av. Rivadavia 2181", barrio: "Balvanera", notas: "Es una de las sucursales de La Golosineria" },
  { zona: "ZONA 3", nombre: "Distribuidora OKS", direccion: "Adolfo Alsina 1556", barrio: "Monserrat", notas: "Hable con Silvia la encargada de compras su numero 11 2724-4969 correo: silvia.m@distrioks.com.ar me indico que pasara el correo con los productos y los precios pero me resalto que el modo de trabajo es reciben la mercancia y pagan cada 15 dias lo facturado. re resalte queno es nuestro modelo de trabajo y que igual le estaria pasando el catalogo." },
  { zona: "ZONA 1", nombre: "Distribuidora Mar y Mar Golosinas", direccion: "Av. Directorio 492", barrio: "Caballito", telefono: "011 4924-7638", url: "golmarymar.com.ar" },
  { zona: "ZONA 2", nombre: "Mercado de Galletitas", direccion: "Parral 101", barrio: "Almagro", notas: "Se habló con Maximiliano tiene 2 sucursales la otra está en Guardia Vieja 3452 indica su whatsapp 11 5052-5466 para recibir el catalogo y lista de precio. resalta que conoce la marca y no trabaja con Snacks solo galletas Mini, Sandwich y individuales. Segunda Visita se habla con Maxi compro mercancia en Mayorista Jaguar de Mini craker una 3 caja para provar le va bien resalta que solo tiene una semana y se indaga por el costo de compra resalta que fue de 847 pesos por paquete lo tiene marcado para la venta en 1500 pesos se ofrece contacto de Venta minorista directo en la Fabrica. el resalta que esta probando el producto con sus clientes y cuando tenga disponibilidad de compra realizara el pedido." },
  { zona: "ZONA 5", nombre: "Hospital Gral. Agudos D. Vélez Sarsfield", direccion: "Pedro Calderón de la Barca 1550", barrio: "Monte Castro", telefono: "147 (GCBA)", url: "buenosaires.gob.ar", notas: "Re agendada" },
  { zona: "ZONA 5", nombre: "Galletitas Belgrano", direccion: "Arismendi 2670, C1427", barrio: "Villa Urquiza", telefono: "011 4523-5531", url: "galletitasbelgrano.com.ar", notas: "ES cliente NEOSOL a simple vista se veian los palet con las cajas. Se notifico a Daniel para indigar quien atiende al cliente. Se verificara a quien pertenece la cuenta antes de abordar." },
  { zona: "ZONA 5", nombre: "Varú - Mayorista de golosinas", direccion: "Bucarelli 2657", barrio: "Villa Urquiza", telefono: "11 6455-3717", notas: "Se habla con Fernanda la Encargada de Tienda indica que los dueños estan de Viajes llegan en 3 semanas. Resalta que no venden galletitas de Agua pero si Snacks de REX, Saladix y en craker venden otra marca. indica el numero de whatsapp 11 64553717 y el correo elbombazo2024@gmail.com se agenda para la visita en 1 mes cuando esten los dueños" },
  { zona: "CORREO", nombre: "Bufano Alimentos", direccion: "CABA (Distribución)", telefono: "11 7502-9310", email: "bufanoalimentos@hotmail.com", url: "lacteosbufano.com.ar" },
  { zona: "ZONA 5", nombre: "Demetrio", direccion: "Av. Triunvirato 4450", barrio: "Villa Urquiza", telefono: "011 4521-3616", url: "demetriomanikis.com.ar", notas: "Se hablo con Luciano el Encargado y dueño se le mostro el catalogo despues de indicar que conocia la marca que es barata en tono de desprecio. Le rebati que no por ser barata era mala le mostre en catalogo y resalto que por ser fabrica seguro habia que comprar en cantidades y igual me indico un correo para que le enviara lista de precio y catalogo lucianoman25@hotmail.com" },
  { zona: "ZONA 2", nombre: "Raz y Cía- Centro de Distribución", direccion: "Manuel Ricardo Trelles 1961", barrio: "Paternal", telefono: "(011) 4586-9100", email: "compras@razycia.com", url: "razycia.ar", notas: "La dirección de la Oficina esta en Heredia 255 llegue a portería me indicaron que escribiera al correo que está en la Pag. WEB ventas@razycia.com se intentó que me indicara algún contacto pero no fue posible. Segunda visita Vigilancia no tiene autorizacion para dar informacion y no tienen contacto con el area de compra" },
  { zona: "ZONA 4", nombre: "La Golosinería ONCE", direccion: "Av. Rivadavia 2504", barrio: "Balvanera", notas: "Solo comercializan productos Importados" },
  { zona: "ZONA 1", nombre: "Distribuidora Aranjuez", direccion: "Av. Eva Perón 6032", barrio: "Mataderos", telefono: "011 4686-2025", notas: "Se habló con Ricardo de Compras indicó que ya habían pasado y dejaron una caja de muestra la repartió entre los trabajadores y no volvieron a pasar así mismo en el 2024 compraron a la fábrica pero les fue mal no se vendió según él la gente no la compraba por no conocer la marca. que igual le pasara el catálogo a distriaranjuez@yahoo.com.ar" },
  { zona: "ZONA 3", nombre: "Distribuidora Lentey", direccion: "Gral. Gregorio Aráoz de Lamadrid 885", barrio: "La BOCA", telefono: "11 5635-3243", notas: "Se mudaron hace mas de un año pero en el lugar no saben para donde o si sigen funcionando" },
  { zona: "ZONA 1", nombre: "Distribuidora del Campo Alimentos", direccion: "Salvigny 1553", barrio: "Parque Chacabuco", telefono: "11 2675-2601", email: "comercial@delcampodistribuidora.com", url: "https://delcampodistribuidora.com/", notas: "Se habla con Martin el responsable de compras resalta que quien tomas las decciones es Ariel el dueño, asi mismo conocen la marca porque la comercializaba en los paquetes individuales dejaron de comprara hace 5 meses porque le exigian comprar 300 cajas y se le vencieron 25 cajas. resalta que le pasara el catalogo y precios y en la charla menciona un plazo de pago de 30 dias y todo en factura A que no piden remitos salvo que se les complique el mes y avecs piden prorrogas de pago. el correo administracion@delcampodistribuidora.com y el whatsapp 11 51803640" },
  { zona: "ZONA 7", nombre: "Distribuidora El Criollo", direccion: "Caracas 2720", barrio: "Flores", telefono: "11 4114-5000", url: "distribuidoraelcriollo.com", notas: "mE ATIENDE mELINA EN RECEPCION INDICA QUE PARA PRESENTAR LOS PRODUCTOS PRIMERO HAY QUE SOLICITAR agenda por mail: compras@elcriollosrl.com resaltando que enviara el catologo por esa via. Segunda visita se habla con Julio indica un numero de contacto 11 41145000. Se realiza un llamado telefonico para compras se esperan 10 min. sin respuesta en el general contesta Ignacio indica que el unico canal de contacto con compras es a traves del mail y que si no contestan es porque estan muy ocupados o no les interesa." },
  { zona: "ZONA 2", nombre: "La Preferida SRL", direccion: "Gral. Manuel A. Rodríguez 2340", barrio: "Paternal", notas: "Me atendió Leo me indico que no atendian proveedores sin previa cita y resaltó que escribiera al correo proveedores@distrilapreferida.com.ar atte. Pablo. segunda visita hable con batista ellos atienden por intercomunicador corroboro el correo es correcto me indica que habla con pablo para que verifique el correo" },
  { zona: "ZONA 2", nombre: "Maxiconsumo S.A.", direccion: "Empedrado 2571", barrio: "Paternal", telefono: "011 4019-6666", url: "maxiconsumo.com", notas: "No OPERATIVO" },
  { zona: "ZONA 2", nombre: "Sweet Market", direccion: "Scalabrini Ortiz 154", barrio: "Villa Crespo", telefono: "11 3037-9090", url: "sweetmarket.com.ar", notas: "La persona de despacho indico que no le interesavan estos productos ya que ellos venden por Mercado Libre, sin embargo me indico un correo del encargado de compras Ramon. gupa78@hotmail.com. Segunda visita no estaba el encargado se confirma el correo pero la persona no tiene mas informacion. Tercera visita una de las empleadas confirma el correo y recibe la Tarjeta con mi numero para hacerlo llegar a Ramon el dueño. resalta que se envie nuevamente el correo" },
  { zona: "ZONA 2", nombre: "Zafiro Distribuidora", direccion: "Caracas 1721", barrio: "Villa del Parque", telefono: "11 4409-7073 / 5491144097073 Wsapp", email: "hola@zafiro.com.ar", url: "zafiro.com.ar", notas: "Se habla con Alvaro que es de Administracion indica que primero hay que pasar un correo a Clara que es la encargada de compras al correo hola@zafiro.com.ar con la presentacion y tarifas para solicitar una reunion" },
  { zona: "ZONA 3", nombre: "Treoland S.A.", direccion: "San José 83", barrio: "Monserrat", telefono: "011 4383-4600", notas: "No existe direccion" },
  { zona: "ZONA 4", nombre: "Open 25", direccion: "Lavelle y reconquista", barrio: "Puerto Madero", telefono: "011 4894-0941", email: "tiendaonline@open25.com.ar", notas: "Ya me indicaron donde esta las oficinas en Tucuman y Reconquista Microcentro. Segunda Visita se habla con Maria es la Repositora de Tienda confirma que es la Principal y estan los Oficinas Administrativas alli indica que no atienden a nadie y resalta que no esta autorizada a dar ninguna informacion me sugiere que le deje mis datos para hacerlos llegar a la Gerente de recursos Humenos para que los canalice al sector indicado. Tercera Visita habla con una persona que no quiso identificarse me indico y resalto que solo por la pagina se solicita o programa una reunion para presentar una propuesta comercial a los cual envie un whatsapp al numero que esta en la Pag. y respondieron enviando un formulario el cual habia que completar y enviar se realizo el mismo." },
  { zona: "CORREO", nombre: "Pedidos YA", direccion: "Av. del Libertador 7208, piso 20, CABA", email: "contacto.ar@pedidosya.com", url: "https://www.pedidosya.com.ar/cadenas/market-pedidosya" },
  { zona: "ZONA 7", nombre: "Ma Distribución", direccion: "Quintana 3657, Lomas del Mirador, CABA", barrio: "CABA", telefono: "11 4193-7600", email: "info@madistribucion.com", url: "https://www.madistribucion.com/", notas: "Hablo con Rodrigo (Vigilancia) me tomo los datos y me indico que el Dueño es el que maneja las compras que nunca esta pero que el le pasa un reporte diario y normalmete le pasa los datos resaltando que si esta interesado se pone en contacto. de igual forma se envio correo por el que esta en el sitio web." },
  { zona: "ZONA 3", nombre: "Cotillomicymac", direccion: "Constitucion 2635", barrio: "San Cristobal", telefono: "11 5499-4505", notas: "se hablo con Marcelo en Dueño de la distribuidora tienen venta al publico le intereso las galletas dulces, los Snack y los individuales. quede en envialle el catologo y unas muestras del producto correo: cotillomicymac@hotmail.com" },
  { zona: "ZONA 3", nombre: "Distribuidora GOLO", direccion: "Contitucion 2469", barrio: "San Cristobal", telefono: "11 38776407", notas: "Se habllo con Jose el encargado de compras indico que estan buscando proveedor de Sandwich tri pack quede en pasar a dejarle algunas muestras me indico su numero de celular para que le pasara el catalogo y precios 11 38776407. Se envia un Mensaje para concretar un llamado con el fin de cerrer un primer pedido." },
  { zona: "ZONA 1", nombre: "GOLO MAX", direccion: "Av. Pres. Dr. Arturo Umberto Illia, San Justo", barrio: "San Justo", notas: "Esta sucursal es solo un despacho para la zona de CABA y la Planta la sede principal está en San Justo Av. Pres. Dr. Arturo Umberto Illia 2379. Segunda Visita primera en San Justo se habla con Mariana la recepcionista indica que el responsable de compras es marcos Alonso y que para agendar una reunion es atraves de correo Malonso@golomax.com.ar se toman datos para enviar correo" },
  { zona: "ZONA 4", nombre: "TICORAL", direccion: "Lavalle 2318", barrio: "ONCE", email: "hernan.rosenblatt@gmail.com", notas: "Se hablo con Alfredo Rosenblatt gerente de compras indico que ya no estan comercializondo galletas de ningun tipo pero le intereso analizar el tema de los Snacks me me indico correo para enviar la informcion tienen 3 locales en ONCE" },
  { zona: "ZONA 4", nombre: "Ciudad Cotillon (Show Party)", direccion: "Lavalle 2257", barrio: "ONCE", telefono: "11 44347963", email: "alfredo@showpartysrl.com", notas: "Se hablo con Alfredo el Responsable de compra se enfoco en conocer el acuerdo de pago se establecio un pedido de mas de 300 cajas se podria hacer un 30/70 con pago del 70% en efectivo el resto en cheque o transferencia a 15 dias, se blanqueo que hay una lista de menos de 300 cajas y me solicito las son aclarandole que el tema del precio por camtidad es estricto y en el caso de menos de 300 el pago es 50/50. asi mismo para incentivar la compra se ofrecio en la compra de mas de 300 cajas 10x1 en Mini. pero aclarando que es solo en la primera compra. segunda Visita no estaba Alfredo el encargado de compras." },
  { zona: "ZONA 4", nombre: "COTY Mania", direccion: "Lavalle 2345", barrio: "ONCE", telefono: "11 3693-4518 / 11 5151-9972", email: "compras@cotymania.com", url: "https://www.cotymania.com/", notas: "Se habla con Vennesa de CAJA indica que son muchas sucursales y el area de comprar solo lo atienden ON-Line por la pagina me da una tarjeta para que me contacte" },
  { zona: "CORREO", nombre: "RES", email: "tienda@res.com.ar", notas: "Se envio Correo para probar si hay respuesta. responden con el correo de la persona responsable se envia correo para buscar oportunidas" },
  { zona: "ZONA 2", nombre: "EL Puente", direccion: "Av. Corriente 6001 Esq. Humboldt", barrio: "Villa Crespo", email: "compras@lacteoselpuente.com.ar", notas: "Se hablo con el encargado de tienda y indico que la parte administratiba esta sobre corriente en una puerta de vidrio. atienden por el intercomunicador Carmen Recepcion indica que hay que enviar un correo a Compras@lacteoselpuente.com.ar" }
]

async function main() {
  console.log(`Start seeding ...`)
  for (const c of initialCompanies) {
    const empresa = await prisma.empresa.create({
      data: c,
    })
    console.log(`Created company with id: ${empresa.id}`)
  }
  console.log(`Seeding finished.`)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
